# Generated by Django 2.2.7 on 2019-11-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network_api', '0003_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptions',
            new_name='description',
        ),
    ]
